name: artus

packages:
  - packages/*

command:
  bootstrap:
    hooks:
      post: melos run generate_localizations 

scripts:
  analyze:
    run: melos exec -- "flutter analyze ."
    description: Run `flutter analyze` in all packages
    
  format:
    run: melos exec -- "dart format --set-exit-if-changed ."
    description: Run `dart format --set-exit-if-changed .` in all packages

  generate_localizations:
    run: cd packages/localizations && flutter gen-l10n && dart format lib/app_localizations/app_localizations.dart
    description: Generates localizations files.


