name: artus
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.1.5
  flutter: 3.13.0

dependencies:
  api:
    path: packages/api
  artus_logger:
    path: packages/artus_logger
  core:
    path: packages/core
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fvm: ^2.4.1
  localizations:
    path: packages/localizations
  mapper:
    path: packages/mapper
  surf_lint_rules: ^3.0.0
  ui_kit:
    path: packages/ui_kit


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.1.1

flutter:
  uses-material-design: true
