name: ui_kit
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  golden_toolkit: ^0.15.0
  surf_lint_rules: ^3.0.0


flutter:
  uses-material-design: true
