name: api
description: Artus API
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mapper:
    path: ../mapper
  surf_lint_rules: ^3.0.0

flutter:
  assets:
    - assets/data.json

