name: core
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  localizations:
    path: ../localizations
  surf_lint_rules: ^3.0.0
  ui_kit:
    path: ../ui_kit
