name: mapper
description: Mapper json to widgets
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: ^3.0.0
  video_player: ^2.7.2
