name: mapper
description: Mapper json to widgets
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: ^3.0.0
  ui_kit:
    path: ../ui_kit
  video_player: ^2.7.2

flutter:
  assets:
    - assets/no_image.png
    - assets/no_video.png
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
        - asset: fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
